# This is a basic workflow to help you get started with Actions

name: deploy-for-main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  UCLOUD_PUBLICKEY : ${{ secrets.UCLOUD_PUBLICKEY }}
  UCLOUD_PRIVATEKEY : ${{ secrets.UCLOUD_PRIVATEKEY }}
  UCLOUD_REGION : ${{ secrets.UCLOUD_REGION }}
  UCLOUD_BUCKET : ${{ secrets.UCLOUD_BUCKET }}
  CI: 1

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info
      
      # Clone 
      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          repository: daocloud/daocloud-api-docs
          path: dao-openapi
          fetch-depth: 0 # Required for mkdocs to be able to display pages last update info
      
      - uses: actions/setup-python@v2
#       - uses: actions/setup-python@v4
        with:
          python-version: 3.x
#           cache: 'pip'
      
      # Add ssh private key
      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
#       - run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

      # Install mkdocs-material-insiders
      - run: git clone git@github.com:DaoCloud/mkdocs-material-insiders.git mkdocs-material
      - run: pip install -e mkdocs-material

      # Runs a single command using the runners shell
      - run: pip install mkdocs-git-revision-date-plugin \
              mkdocs-mermaid2-plugin \
              mkdocs-rss-plugin \
              mkdocs-minify-plugin \
              mkdocs-macros-plugin \
              mkdocs-git-revision-date-localized-plugin \
              mkdocs-awesome-pages-plugin \
              mkdocs-redirects \
              mkdocs-print-site-plugin \
              mkdocs-swagger-ui-tag \
              pyyaml
      
      # add custom plugin with pdf support
      - run: pip install git+https://github.com/SAMZONG/mkdocs-with-pdf-support-material-v8

      # merged openapi docs
      - run: cp -av dao-openapi/docs/openapi docs/zh/docs/
      - run: python scripts/merged_nav.py

      # build docs
      - run: pwd
      - run: mkdocs build -f docs/zh/mkdocs.yml -d ../../public/
      - run: mkdocs build -f docs/en/mkdocs.yml -d ../../public/en/

      # upload to ucloud bucket
      - run: cd public && pwd && python ../scripts/upload-ucloud.py \
                public_key=$UCLOUD_PUBLICKEY \
                private_key=$UCLOUD_PRIVATEKEY \
                region=$UCLOUD_REGION \
                bucket=$UCLOUD_BUCKET

      # refresh docs site cdn cache
      - run: python scripts/refresh_cdn_cache.py \
            publickey=$UCLOUD_PUBLICKEY \
            privatekey=$UCLOUD_PRIVATEKEY
